version: '3.9'
services:
  redis1:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7000:7000"

  redis2:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"

  redis3:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"

  redis4:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node4.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"

  redis5:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node5.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"

  redis6:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node6.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"

  redis-cluster:
    tty: true
    image: redis:6
    network_mode: host
    # command: bash -c "
    #    echo yes | redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 --cluster-replicas 1      
    #   "
    command: bash -c "
       echo yes | redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1      
      "