version: '3.9'
services:
  redis1:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7000:7000"

  redis2:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"

  redis3:
    image: redis:6
    network_mode: host
    volumes:
      - ./config/node3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"

  redis-cluster:
    tty: true
    image: redis:6
    network_mode: host
    command: bash -c "
       echo yes | redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 --cluster-replicas 0      
      "