FROM golang:1.25 AS build
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /demo-bloom-filter main.go


FROM alpine:latest
WORKDIR /root/
EXPOSE 8080
COPY --from=build /demo-bloom-filter .
CMD ["./demo-bloom-filter"]